title: "Arduino: Interpreting whistle commands"
author: "Hans Kruijsse"
description: "Blogpage presenting an Arduino project of mine."
more: "read more »"
url: "https://hans-k.github.io/"
baseurl: "/blog"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/niklasbuschmann/contrast"
  - envelope: "mailto:h.kruysse@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
